// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Infrastructure.Data;

#nullable disable

namespace UserService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Domain.Entities.DoctorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicDegree")
                        .HasColumnType("text");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CertificateExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiplomaNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiplomaSeries")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoctorProfiles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.DoctorScheduleSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConsultationSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationSessionId");

                    b.HasIndex("DoctorProfileId", "StartsAt");

                    b.ToTable("DoctorScheduleSlots");
                });

            modelBuilder.Entity("UserService.Domain.Entities.OrganizationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .HasColumnType("text");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OGRN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrganizationProfiles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<int?>("BloodType")
                        .HasColumnType("integer");

                    b.Property<string>("DoctorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SNILS")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(221),
                            Description = "Просмотр своей медицинской истории",
                            Name = "self.history.read",
                            Resource = "History"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Action = "View",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1508),
                            Description = "Просмотр своего профиля",
                            Name = "self.profile.view",
                            Resource = "Profile"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Action = "Edit",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1528),
                            Description = "Редактирование своего профиля",
                            Name = "self.profile.edit",
                            Resource = "Profile"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1570),
                            Description = "Просмотр истории пациента (для врача)",
                            Name = "patient.history.read",
                            Resource = "History"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1575),
                            Description = "Выписка рецептов",
                            Name = "prescription.create",
                            Resource = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Action = "View",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1654),
                            Description = "Просмотр рецептов",
                            Name = "prescription.view",
                            Resource = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Action = "Dispense",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1658),
                            Description = "Выдача лекарств по рецепту",
                            Name = "prescription.dispense",
                            Resource = "Prescription"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1714),
                            Description = "Создание заказа на анализы",
                            Name = "lab.order.create",
                            Resource = "Lab"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Action = "Upload",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1719),
                            Description = "Загрузка результатов анализов",
                            Name = "lab.results.upload",
                            Resource = "Lab"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Action = "View",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1723),
                            Description = "Просмотр результатов анализов",
                            Name = "lab.results.view",
                            Resource = "Lab"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Action = "Start",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1726),
                            Description = "Начало консультации",
                            Name = "consultation.start",
                            Resource = "Consultation"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Action = "Join",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1729),
                            Description = "Подключение к консультации",
                            Name = "consultation.join",
                            Resource = "Consultation"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Action = "Manage",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1732),
                            Description = "Управление пользователями организации",
                            Name = "org.users.manage",
                            Resource = "Organization"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Action = "Manage",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1734),
                            Description = "Управление расписанием организации",
                            Name = "org.schedule.manage",
                            Resource = "Organization"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Action = "View",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1737),
                            Description = "Просмотр финансовой отчетности",
                            Name = "org.finance.view",
                            Resource = "Organization"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Action = "ViewAll",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1743),
                            Description = "Просмотр всех пользователей",
                            Name = "users.view.all",
                            Resource = "Users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Action = "Block",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1747),
                            Description = "Блокировка пользователей",
                            Name = "users.block",
                            Resource = "Users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Action = "Manage",
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(1751),
                            Description = "Управление настройками системы",
                            Name = "system.settings.manage",
                            Resource = "System"
                        });
                });

            modelBuilder.Entity("UserService.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProfileType")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(8495),
                            Description = "Обычный пациент",
                            IsSystem = true,
                            Name = "Patient"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(9193),
                            Description = "Врач",
                            IsSystem = true,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(9197),
                            Description = "Администратор клиники",
                            IsSystem = true,
                            Name = "ClinicAdmin"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(9201),
                            Description = "Сотрудник лаборатории",
                            IsSystem = true,
                            Name = "LabEmployee"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(9203),
                            Description = "Сотрудник аптеки",
                            IsSystem = true,
                            Name = "PharmacyEmployee"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(9213),
                            Description = "Администратор платформы",
                            IsSystem = true,
                            Name = "PlatformAdmin"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 24, 16, 5, 16, 907, DateTimeKind.Utc).AddTicks(9215),
                            Description = "Суперадминистратор",
                            IsSystem = true,
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("UserService.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("UserService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.DoctorProfile", b =>
                {
                    b.HasOne("UserService.Domain.Entities.Profile", "Profile")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("UserService.Domain.Entities.DoctorProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.DoctorScheduleSlot", b =>
                {
                    b.HasOne("UserService.Domain.Entities.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorProfile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.OrganizationProfile", b =>
                {
                    b.HasOne("UserService.Domain.Entities.Profile", "Profile")
                        .WithOne("OrganizationProfile")
                        .HasForeignKey("UserService.Domain.Entities.OrganizationProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UserService.Domain.Entities.Address", "LegalAddress", b1 =>
                        {
                            b1.Property<Guid>("OrganizationProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Area")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("Flat")
                                .HasColumnType("text");

                            b1.Property<string>("House")
                                .HasColumnType("text");

                            b1.Property<string>("PostCode")
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("OrganizationProfileId");

                            b1.ToTable("OrganizationProfiles");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationProfileId");
                        });

                    b.Navigation("LegalAddress");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.PatientProfile", b =>
                {
                    b.HasOne("UserService.Domain.Entities.Profile", "Profile")
                        .WithOne("PatientProfile")
                        .HasForeignKey("UserService.Domain.Entities.PatientProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("UserService.Domain.Entities.Profile", b =>
                {
                    b.HasOne("UserService.Domain.Entities.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("UserService.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserService.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("UserService.Domain.Entities.Profile", "Profile")
                        .WithMany("UserRoles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("UserService.Domain.Entities.Profile", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("OrganizationProfile");

                    b.Navigation("PatientProfile");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.Domain.Entities.User", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
