services:
  postgres-prescription:
    image: postgres:15
    container_name: vitals-postgres-prescription
    environment:
      POSTGRES_DB: PrescriptionDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5438:5432"
    volumes:
      - postgres-prescription-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vitals-network

  prescription.api:
    build:
      context: .
      dockerfile: PrescriptionService.API/Dockerfile
    container_name: vitals-prescription
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres-prescription;Port=5432;Database=PrescriptionDb;Username=postgres;Password=postgres123
      - MedicalRecordService__BaseUrl=http://medicalrecordservice.api:80
      - Jwt__JwksUrl=http://authservice.api:80/internal/jwks
    ports:
      - "5007:80"
    depends_on:
      postgres-prescription:
        condition: service_healthy
    networks:
      - vitals-network

volumes:
  postgres-prescription-data:

networks:
  vitals-network:
    driver: bridge
